In [2]:
import pandas as pd
import selenium
from selenium import webdriver
from bs4 import BeautifulSoup
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import warnings
warnings.filterwarnings('ignore')
import time
from selenium.common.exceptions import ElementClickInterceptedException,NoSuchElementException

Q1

In [3]:
driver = webdriver.Chrome()
driver.get("https://www.amazon.in")
driver.maximize_window()
time.sleep(2)
search_bar = driver.find_element(By.ID,"twotabsearchtextbox")
item = input("Enter item to search")
search_bar.send_keys(item)
search_bar.send_keys(Keys.ENTER)

Enter item to searchsun glasses

Q2

In [15]:
brand_name = []
product_name = []
prices = []
product_url = []
start = 0
end = 3
for page in range(start,end):
    brand_tag = driver.find_elements(By.XPATH,'//h2[@class="a-size-mini s-line-clamp-1"]')
    product_tag = driver.find_elements(By.XPATH,'//h2[@class="a-size-mini a-spacing-none a-color-base s-line-clamp-2"]')
    price_tag = driver.find_elements(By.XPATH,'//a[@class="a-link-normal s-no-hover s-underline-text s-underline-link-text s-link-style a-text-normal"]/span[1]')
    url = driver.find_elements(By.XPATH,'//a[@class="a-link-normal s-underline-text s-underline-link-text s-link-style a-text-normal"]')
    
    for i in brand_tag:
        brand_name.append(i.text)
    for i in product_tag:
        product_name.append(i.text)
    for i in price_tag:
        price = i.text
        prices.append(price.replace("â‚¹",""))
   
    
    for i in url:
        product_url.append(i.get_attribute('href'))
    next_button = driver.find_element(By.XPATH,'//*[text()="Next"]')
    next_button.click()
    time.sleep(5) 

return_exchange = []
for i  in product_url:
    driver.get(i)
    time.sleep(5)
    try:
        exchange = driver.find_element(By.XPATH,'//span[@class="a-declarative"]/div[2]/span')
        return_exchange.append(exchange.text)
    except NoSuchElementException:
        return_exchange.append('-')
driver.close()
        
df = pd.DataFrame({"Brand Name":brand_name,"Name of the product":product_name,"Price":prices,"Return/Exchange":return_exchange,"Product URL":product_url})
df

,Brand Name,Name of the product,Price,Return/Exchange,Product URL
0,VINCENT CHASE EYEWEAR,Vincent Chase By Lenskart | Full Rim Square Br...,548,10 days Return & Exchange,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
1,LAZZARO,UV Protection Sunglasses for Men and Women Cla...,899,10 days Return & Exchange,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
2,VINCENT CHASE EYEWEAR,By Lenskart | Full Rim Round Branded Latest an...,699,10 days Return & Exchange,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
3,LAZZARO,UV Protection Coating Rectangular Sunglasses f...,899,10 days Return & Exchange,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
4,Sheomy,Unisex Combo offer pack of 5 shades glasses Bl...,499,10 days Return & Exchange,https://www.amazon.in/Sheomy-glasses-MC-Rectan...
...,...,...,...,...,...
195,CREEK,Premium Square Polarized Sunglasses | UV Prote...,498,10 days Return & Exchange,https://www.amazon.in/CREEK-Polarized-Sunglass...
196,Intellilens,| Branded Sunglasses | Aviator,629,10 days Return & Exchange,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
197,VELOCITY STUDIO,VELOCITY UV Protective Aviator Designed Stylis...,"2,750",10 days Returnable,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
198,Eyewearlabs,OKNO | Polarized Full Rim Square Branded Styli...,"1,599",10 days Return & Exchange,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
199,grey jack,Polarized Aviator Sunglasses lightweight Styli...,799,10 days Return & Exchange,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...

In [ ]:
#to save dataframe in csv
df2 = df.to_csv("product_details.csv",index=False)

Q3

In [16]:
driver = webdriver.Chrome()
image =[]
items = ["fruits","cars","machine learning","guitar","cakes"]
for i in items:
    driver.get("https://images.google.com/")
    driver.maximize_window()
    search = driver.find_element(By.XPATH,'//textarea[@class="gLFyf"]')
    search.send_keys(i)
    search.send_keys(Keys.ENTER)
    time.sleep(3)
    images = driver.find_elements(By.XPATH,'//img[@class="YQ4gaf"]')
    for k in images[0:10]:
        q = k.get_attribute('src')
        image.append(q)
driver.close()
   
df = pd.DataFrame({"Image":image})
df

                                                Image
0   data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
1   data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
2   data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
3   data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
4   data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
5   data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
6   data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
7   data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...
8   data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
9   data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
10  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
11  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
12  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
13  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
14  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
15  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
16  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
17  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
18  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
19  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
20  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
21  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
22  data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...
23  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
24  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
25  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
26  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
27  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
28  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
29  data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...
30  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
31  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
32  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
33  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
34  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
35  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
36  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
37  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
38  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
39  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
40  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
41  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
42  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
43  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
44  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
45  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
46  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
47  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
48  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...
49  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...

Q4.

In [15]:
driver = webdriver.Chrome()
driver.get("https://flipkart.com")
driver.maximize_window()

search = driver.find_element(By.XPATH,'//input[@class="Pke_EE"]')
search.send_keys("smartphone")
search.send_keys(Keys.ENTER)
time.sleep(5)

brand_name = []
name_tag = driver.find_elements(By.XPATH,'//div[@class="KzDlHZ"]')
for i in name_tag:
    brand_name.append(i.text)
brand_name

['Motorola Edge 50 Pro 5G with 125W Charger (Luxe Lavender, 256 GB)',
 'Motorola Edge 50 Fusion (Hot Pink, 256 GB)',
 'Motorola Edge 50 Fusion (Marshmallow Blue, 256 GB)',
 'Motorola Edge 50 Pro 5G with 125W Charger (Black Beauty, 256 GB)',
 'realme P2 Pro 5G (Eagle Grey, 128 GB)',
 'vivo T3 Ultra (Lunar Gray, 128 GB)',
 'Motorola Edge 50 Fusion (Forest Green, 128 GB)',
 'Motorola g45 5G (Brilliant Green, 128 GB)',
 'Motorola Edge 50 Fusion (Forest Green, 256 GB)',
 'Motorola Edge 50 Fusion (Forest Blue, 128 GB)',
 'Motorola Edge 50 Pro 5G with 125W Charger (Vanilla Cream, 256 GB)',
 'itel A50 (Lime Green, 64 GB)',
 'Motorola Edge 50 Pro 5G with 125W Charger (Caneel Bay, 256 GB)',
 'Motorola g45 5G (Brilliant Blue, 128 GB)',
 'Motorola Edge 50 Fusion (Marshmallow Blue, 128 GB)',
 'Motorola Edge 50 Fusion (Forest Blue, 256 GB)',
 'Motorola Edge 50 Fusion (Hot Pink, 128 GB)',
 'Motorola g45 5G (Viva Magenta, 128 GB)',
 'Motorola g45 5G (Brilliant Green, 128 GB)',
 'Motorola g45 5G (Viva Magenta, 128 GB)',
 'REDMI 12 (Pastel Blue, 128 GB)',
 'Apple iPhone 15 (Pink, 128 GB)',
 'vivo T3 Lite 5G (Vibrant Green, 128 GB)',
 'vivo T3 Lite 5G (Majestic Black, 128 GB)']

Q7

In [17]:
driver = webdriver.Chrome()
driver.get("https://www.forbes.com")
driver.maximize_window()
time.sleep(5)

path = driver.find_element(By.XPATH,'//div[@class="dN9h-rXs"]/div')
path.click()
time.sleep(5)

path_select = driver.find_element(By.XPATH,'//li[@class="QpfB0oZe ocPoioVz primary"][1]/div/span')
path_select.click()
time.sleep(2)

path_selector = driver.find_element(By.XPATH,'//div[@class="A6l1kjob G-fdXOrK"]/div[3]/ul/li[1]/a')
path_selector.click()
time.sleep(5)

rank = []
name = []
networth = []
industry = []

page_start = 1
page_end = 15
for page in range(page_start,page_end):
    rank_tag = driver.find_elements(By.XPATH,'//div[@class="Table_rank__X4MKf"]/div[1]')
    for i in rank_tag:
        ranks = i.text
        rank.append(ranks.replace('.',''))


    name_tag = driver.find_elements(By.XPATH,'//div[@class="Table_personName__Bus2E"]')
    for i in name_tag:
        name.append(i.text)    


    networth_tag = driver.find_elements(By.XPATH,'//div[@class="Table_finalWorth__UZA6k"]/span')
    for i in networth_tag:
        networths = i.text
        networth.append(networths.replace("$",""))


    industry_tag= driver.find_elements(By.XPATH,'//div[@role="cell"][4]')
    for i in industry_tag:
        industry.append(i.text)
        
    try:
        next_button = driver.find_element(By.XPATH,'//button[@class="t7aCs7DQ _0BYTGi5u TNAO5JyH bMlalnxk _5nHoWK7c"][2]')
        next_button.click()
    except ElementClickInterceptedException as e:
        next_button = driver.find_element(By.XPATH,'//button[@class="t7aCs7DQ _0BYTGi5u TNAO5JyH bMlalnxk _5nHoWK7c"][1]')
        next_button.click()
        
driver.close()    
df = pd.DataFrame({"RANK":rank,"NAME":name,"NET WORTH":networth,"INDUSTRY":industry})
df

      RANK                      NAME NET WORTH INDUSTRY
0        1  Bernard Arnault & family     233 B       75
1        2                 Elon Musk     195 B       52
2        3                Jeff Bezos     194 B       60
3        4           Mark Zuckerberg     177 B       39
4        5             Larry Ellison     141 B       79
...    ...                       ...       ...      ...
2795  2287   Horst Wortmann & family     1.3 B       82
2796  2287               Wu Chung-yi     1.3 B       68
2797  2287                 Ingrid Wu     1.3 B      N/A
2798  2287        Wu Xushun & family     1.3 B       75
2799  2287               Wu Yingming     1.3 B       57

[2800 rows x 4 columns]

Q8

In [22]:
driver = webdriver.Chrome()
driver.get("https://www.youtube.com/watch?v=cE-Ej1ycXtk")
driver.maximize_window()


comments = []
upvote = []
time = []
comment_tag = driver.find_elements(By.XPATH,'//yt-attributed-string[@id="content-text"]')
vote_tag = driver.find_elements(By.XPATH,'//span[@id="vote-count-middle"]')
time_tag = driver.find_elements(By.XPATH,'//span[@class="style-scope ytd-comment-view-model"]/a')
for i in comment_tag:
    comments.append(i.text)
    
for i in vote_tag:
    vote = i.text
    upvote.append(vote)
    
for i in time_tag:
    time.append(i.text)
driver.close()
    
df = pd.DataFrame({"Comments":comments,"UpVote":upvote,"Time":time})
df

Empty DataFrame
Columns: [Comments, UpVote, Time]
Index: []

Q9

In [23]:
driver = webdriver.Chrome()
driver.get("https://www.hostelworld.com/")
driver.maximize_window()

location = driver.find_element(By.XPATH,'/html/body/div[3]/div/div[3]/main/header/div/div[2]/div[1]/div[1]/div/div[1]/div/div/div[2]/label/input')
location.send_keys("London")
auto_popup = driver.find_elements(By.XPATH,'/html/body/div[3]/div/div[3]/main/header/div/div[2]/div[1]/div[1]/div/div[1]/div[2]/div/ul/li[2]/button')
auto_popup.click()
search = driver.find_element(By.XPATH,'//button[@class="btn-content large-button"]')
search.click()

hostel_name = []
distance_from_city = []
rating = []
review = []


name_tag = driver.find_elements(By.XPATH,'//div[@class="property-name"]/span')
distance_tag = driver.find_elements(By.XPATH,'//div[@class="property-distance"]/span[2]')
rating_tag = driver.find_elements(By.XPATH,'//div[@class="rating medium theme-null"]/span[1]')
review_tag = driver.find_elements(By.XPATH,'//div[@class="rating medium theme-null"]/span[3]')

for i in name_tag:
    hostel_name.append(i.text)
    
for i in distance_tag:
    distance = i.text
    distance_from_city.append(distance.replace("- ",""))
    
for i in rating_tag:
    rating.append(i.text)

for i in review_tag:
    reviews = i.text.replace("(","")
    review.append(reviews.replace(")",""))
    

driver.close()    
df = pd.DataFrame({"Hostel Name":hostel_name,"Distance":distance,"Rating":rating})
df

                                 Hostel Name                  Distance Rating
0                Wombat's City Hostel London  - 8.2km from city centre    9.3
1                       Urbany Hostel London  - 8.2km from city centre    9.6
2   St Christopher's Village - London Bridge  - 8.2km from city centre    7.9
3                           Generator London  - 8.2km from city centre    7.0
4                                   Clink261  - 8.2km from city centre    8.1
5                           Astor Museum Inn  - 8.2km from city centre    8.8
6                           NX London Hostel  - 8.2km from city centre    7.1
7               No.8 Willesden Hostel London  - 8.2km from city centre    7.2
8    Safestay London Kensington Holland Park  - 8.2km from city centre    7.1
9                Smart Russell Square Hostel  - 8.2km from city centre    7.5
10                   Queen Elizabeth Chelsea  - 8.2km from city centre    7.5
11                   Saint James Backpackers  - 8.2km from city centre    8.1
12                           Astor Hyde Park  - 8.2km from city centre    7.8
13                            Phoenix Hostel  - 8.2km from city centre    6.9
14                Smart Hyde Park Inn Hostel  - 8.2km from city centre    7.6
15                            Astor Victoria  - 8.2km from city centre    7.3
16              St Christopher's Hammersmith  - 8.2km from city centre    7.7
17                Kabannas London St Pancras  - 8.2km from city centre    8.1
18                   St Christopher's Camden  - 8.2km from city centre    7.5
19                St Christopher's Greenwich  - 8.2km from city centre    7.7
20                                Park Villa  - 8.2km from city centre    9.0
21                          Astor Kensington  - 8.2km from city centre    7.5
22           St Christopher's Shepherds Bush  - 8.2km from city centre    7.2
23                         Bell House Hostel  - 8.2km from city centre    6.5
24       PubLove @ The White Ferry, Victoria  - 8.2km from city centre    7.6
25      PubLove @ The Steam Engine, Waterloo  - 8.2km from city centre    7.5
26                          London365 Hostel  - 8.2km from city centre    4.8
27       PubLove @ The Green Man, Paddington  - 8.2km from city centre    7.4
28                        Book a Bed Hostels  - 8.2km from city centre    7.3
29                  Kensal Green Backpackers  - 8.2km from city centre    7.0

In [11]:
print(review)

['16995', '1454', '13262', '8466', '791', '9627', '2124', '5333', '1978', '10357', '3870', '2015', '12438', '4877', '6898', '15202', '4511', '3090', '4221', '3525', '947', '6640', '893', '240', '480', '499', '469', '1333', '3761']

Q6

In [13]:
driver= webdriver.Chrome()
driver.get("https://www.digit.in")
driver.maximize_window()

search = driver.find_element(By.XPATH,'//input[@id="woocommerce-product-search-field-0"]')
search.send_keys("gaming laptops")
search.send_keys(Keys.ENTER)

name = []
price = []
name_tag = driver.find_elements(By.XPATH,'//h3[@class=" text-clamp text-clamp-2"]/a')
price_tag = driver.find_elements(By.XPATH,'//div[@class="cegg-price-row"]/div[1]')
for i in name_tag:
    name.append(i.text)
    
for i in price_tag:
    price.append(i.text)
    
print("Name",name)
print("price",price)
driver.close()

Name ['Lenovo IdeaPad Gaming 3 15IAH7', 'Lenovo IdeaPad Gaming 3i', 'Alienware x14 Gaming Laptop', 'MSI Gaming Raider', 'Lenovo Legion 7', 'Dell 15 (2021) i5-10200H']
price ['Rs. 263', 'out of stock', 'Rs. 309', 'out of stock']

Q5

In [46]:
driver = webdriver.Chrome()
driver.get("https://www.google.com/maps")
driver.maximize_window()
time.sleep(5)
search = driver.find_element(By.ID,'searchboxinput')
search.clear()
search.send_keys("mandya")
search_button = driver.find_element(By.ID,'searchbox-searchbutton')
search_button.click()
time.sleep(5)
url_coordinates = driver.current_url
coordinates = url_coordinates.split('@')[1].split(',')[0:2]
latitude = coordinates[0]
longitude = coordinates[1]
print("Latitude:",latitude)
print("Longitude:",longitude)

Latitude: 12.5224995
Longitude: 76.8761197